monitor = , 1920x1080@144, auto, 1

# keybinds
unbind = Super, K
unbind = Super, L

# change window focusing with vim-like hjkl
bind = Super, H, movefocus, l
bind = Super, J, movefocus, d
bind = Super, K, movefocus, u
bind = Super, L, movefocus, r

# change window focusing with vim-like hjkl
bind = Super, Shift+H, movefocus, l, swap
bind = Super, Shift+J, movefocus, d, swap
bind = Super, Shift+K, movefocus, u, swap
bind = Super, Shift+L, movefocus, r, swap

# unbind change the sleep
unbind bind = Super+Shift #, L, exec, systemctl suspend-then-hibernate
bind = Super+Shift, Period, exec, systemctl suspend-then-hibernate
