monitor = , 1920x1080@144, auto, 1

# keybinds
unbind = Super, K
unbind = Super, L

# change window focusing with vim-like hjkl
bind = Super, H, movefocus, l
bind = Super, J, movefocus, d
bind = Super, K, movefocus, u
bind = Super, L, movefocus, r

# change window focusing with vim-like hjkl
bind = Super+Shift, H, movewindow, l
bind = Super+Shift, J, movewindow, d
bind = Super+Shift, K, movewindow, u
bind = Super+Shift, L, movewindow, r

# unbind change the sleep
unbind = Super+Shift, L #, L, exec, systemctl suspend-then-hibernate
bind = Super+Shift, Period, exec, systemctl suspend-then-hibernate
